// Copyright 2022 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://github.com/onexstack/onex.
//

package app

import (
	"fmt"

	"github.com/onexstack/onexstack/pkg/app"
	utilruntime "k8s.io/apimachinery/pkg/util/runtime"
	genericapiserver "k8s.io/apiserver/pkg/server"
	logsapi "k8s.io/component-base/logs/api/v1"

	"github.com/onexstack/onex/cmd/onex-pump/app/options"
	"github.com/onexstack/onex/internal/pkg/feature"
)

func init() {
	utilruntime.Must(logsapi.AddFeatureGates(feature.DefaultMutableFeatureGate))
}

const commandDesc = `Pump is a pluggable analytics purger to move Analytics generated by your onex nodes to any back-end.

Find more onex-pump information at:
    https://github.com/onexstack/onex/blob/master/docs/guide/en-US/cmd/onex-pump.md`

// NewApp creates and returns a new App object with default parameters.
func NewApp() *app.App {
	opts := options.NewServerOptions()
	application := app.NewApp(
		"onex-pump",
		"Launch a onex pump server",
		app.WithDescription(commandDesc),
		app.WithOptions(opts),
		app.WithDefaultValidArgs(),
		app.WithRunFunc(run(opts)),
		app.WithHealthCheckFunc(func() error {
			go opts.HealthOptions.ServeHealthCheck()
			return nil
		}),
	)

	return application
}

// run contains the main logic for initializing and running the server.
func run(opts *options.ServerOptions) app.RunFunc {
	return func() error {
		// Load the configuration options
		cfg, err := opts.Config()
		if err != nil {
			return fmt.Errorf("failed to load configuration: %w", err)
		}

		ctx := genericapiserver.SetupSignalContext()

		// Build the server using the configuration
		server, err := cfg.NewServer(ctx)
		if err != nil {
			return fmt.Errorf("failed to create server: %w", err)
		}

		// Run the server with signal context for graceful shutdown
		return server.Run(ctx)
	}
}
