// This file defines the Protobuf messages for managing Miners.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: gateway/v1/miner.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Miner represents a miner with its metadata.
type Miner struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName string                 `protobuf:"bytes,2,opt,name=displayName,proto3" json:"displayName,omitempty"`
	MinerType   string                 `protobuf:"bytes,3,opt,name=minerType,proto3" json:"minerType,omitempty"`
	ChainName   string                 `protobuf:"bytes,4,opt,name=chainName,proto3" json:"chainName,omitempty"`
	DataDir     string                 `protobuf:"bytes,5,opt,name=dataDir,proto3" json:"dataDir,omitempty"`
	Status      string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	// CreatedAt is the timestamp when the miner was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// UpdatedAt is the timestamp when the miner was last updated.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Miner) Reset() {
	*x = Miner{}
	mi := &file_gateway_v1_miner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Miner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Miner) ProtoMessage() {}

func (x *Miner) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_miner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Miner.ProtoReflect.Descriptor instead.
func (*Miner) Descriptor() ([]byte, []int) {
	return file_gateway_v1_miner_proto_rawDescGZIP(), []int{0}
}

func (x *Miner) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Miner) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Miner) GetMinerType() string {
	if x != nil {
		return x.MinerType
	}
	return ""
}

func (x *Miner) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

func (x *Miner) GetDataDir() string {
	if x != nil {
		return x.DataDir
	}
	return ""
}

func (x *Miner) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Miner) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Miner) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateMinerRequest represents the request message for creating a new miner.
type CreateMinerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayName   string                 `protobuf:"bytes,1,opt,name=displayName,proto3" json:"displayName,omitempty"`
	MinerType     string                 `protobuf:"bytes,2,opt,name=minerType,proto3" json:"minerType,omitempty"`
	ChainName     string                 `protobuf:"bytes,3,opt,name=chainName,proto3" json:"chainName,omitempty"`
	DataDir       string                 `protobuf:"bytes,4,opt,name=dataDir,proto3" json:"dataDir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMinerRequest) Reset() {
	*x = CreateMinerRequest{}
	mi := &file_gateway_v1_miner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMinerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMinerRequest) ProtoMessage() {}

func (x *CreateMinerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_miner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMinerRequest.ProtoReflect.Descriptor instead.
func (*CreateMinerRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_miner_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMinerRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateMinerRequest) GetMinerType() string {
	if x != nil {
		return x.MinerType
	}
	return ""
}

func (x *CreateMinerRequest) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

func (x *CreateMinerRequest) GetDataDir() string {
	if x != nil {
		return x.DataDir
	}
	return ""
}

// UpdateMinerRequest represents the request message for updating an existing miner.
type UpdateMinerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   *string                `protobuf:"bytes,2,opt,name=displayName,proto3,oneof" json:"displayName,omitempty"`
	DeletePolicy  *string                `protobuf:"bytes,3,opt,name=deletePolicy,proto3,oneof" json:"deletePolicy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMinerRequest) Reset() {
	*x = UpdateMinerRequest{}
	mi := &file_gateway_v1_miner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMinerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMinerRequest) ProtoMessage() {}

func (x *UpdateMinerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_miner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMinerRequest.ProtoReflect.Descriptor instead.
func (*UpdateMinerRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_miner_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateMinerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateMinerRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *UpdateMinerRequest) GetDeletePolicy() string {
	if x != nil && x.DeletePolicy != nil {
		return *x.DeletePolicy
	}
	return ""
}

// DeleteMinerRequest represents the request message for deleting one or more miners.
type DeleteMinerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMinerRequest) Reset() {
	*x = DeleteMinerRequest{}
	mi := &file_gateway_v1_miner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMinerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMinerRequest) ProtoMessage() {}

func (x *DeleteMinerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_miner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMinerRequest.ProtoReflect.Descriptor instead.
func (*DeleteMinerRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_miner_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteMinerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// DeleteMinerResponse represents the response message for a successful miner deletion.
type DeleteMinerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMinerResponse) Reset() {
	*x = DeleteMinerResponse{}
	mi := &file_gateway_v1_miner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMinerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMinerResponse) ProtoMessage() {}

func (x *DeleteMinerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_miner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMinerResponse.ProtoReflect.Descriptor instead.
func (*DeleteMinerResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_miner_proto_rawDescGZIP(), []int{4}
}

// GetMinerRequest represents the request message for retrieving a specific miner.
type GetMinerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the unique identifier of the miner to retrieve.
	// @gotags: uri:"name"
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" uri:"name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMinerRequest) Reset() {
	*x = GetMinerRequest{}
	mi := &file_gateway_v1_miner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMinerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMinerRequest) ProtoMessage() {}

func (x *GetMinerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_miner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMinerRequest.ProtoReflect.Descriptor instead.
func (*GetMinerRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_miner_proto_rawDescGZIP(), []int{5}
}

func (x *GetMinerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GetMinerResponse represents the response message for a successful retrieval of a miner.
type GetMinerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Miner is the retrieved miner object.
	Miner         *Miner `protobuf:"bytes,1,opt,name=miner,proto3" json:"miner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMinerResponse) Reset() {
	*x = GetMinerResponse{}
	mi := &file_gateway_v1_miner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMinerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMinerResponse) ProtoMessage() {}

func (x *GetMinerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_miner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMinerResponse.ProtoReflect.Descriptor instead.
func (*GetMinerResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_miner_proto_rawDescGZIP(), []int{6}
}

func (x *GetMinerResponse) GetMiner() *Miner {
	if x != nil {
		return x.Miner
	}
	return nil
}

// ListMinerRequest represents the request message for listing miners
// with pagination and optional filters.
type ListMinerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Offset is the starting point of the list for pagination.
	// @gotags: form:"offset"
	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty" form:"offset"`
	// Limit is the maximum number of miners to return.
	// @gotags: form:"limit"
	Limit         int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty" form:"limit"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMinerRequest) Reset() {
	*x = ListMinerRequest{}
	mi := &file_gateway_v1_miner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMinerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMinerRequest) ProtoMessage() {}

func (x *ListMinerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_miner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMinerRequest.ProtoReflect.Descriptor instead.
func (*ListMinerRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_miner_proto_rawDescGZIP(), []int{7}
}

func (x *ListMinerRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListMinerRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListMinerResponse represents the response message for listing miners.
type ListMinerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TotalCount is the total number of miners matching the query.
	Total int64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// Miner is the list of miners in the current page.
	Miners        []*Miner `protobuf:"bytes,2,rep,name=miners,proto3" json:"miners,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMinerResponse) Reset() {
	*x = ListMinerResponse{}
	mi := &file_gateway_v1_miner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMinerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMinerResponse) ProtoMessage() {}

func (x *ListMinerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_miner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMinerResponse.ProtoReflect.Descriptor instead.
func (*ListMinerResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_miner_proto_rawDescGZIP(), []int{8}
}

func (x *ListMinerResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListMinerResponse) GetMiners() []*Miner {
	if x != nil {
		return x.Miners
	}
	return nil
}

var File_gateway_v1_miner_proto protoreflect.FileDescriptor

var file_gateway_v1_miner_proto_rawDesc = []byte{
	0x0a, 0x16, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x69, 0x6e,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9f, 0x02, 0x0a, 0x05, 0x4d, 0x69, 0x6e, 0x65, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x61, 0x74, 0x61, 0x44, 0x69, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x64, 0x61, 0x74, 0x61, 0x44, 0x69, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x38, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x38, 0x0a,
	0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x8c, 0x01, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4d, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x64, 0x61, 0x74, 0x61, 0x44, 0x69, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64,
	0x61, 0x74, 0x61, 0x44, 0x69, 0x72, 0x22, 0x99, 0x01, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4d, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x25, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x27, 0x0a, 0x0c, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01,
	0x52, 0x0c, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x88, 0x01,
	0x01, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x22, 0x28, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x69, 0x6e, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x15, 0x0a, 0x13,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x25, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4d, 0x69, 0x6e, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3b, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x4d, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27,
	0x0a, 0x05, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x69, 0x6e, 0x65, 0x72,
	0x52, 0x05, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x22, 0x40, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x4d,
	0x69, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x54, 0x0a, 0x11, 0x4c, 0x69, 0x73,
	0x74, 0x4d, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x12, 0x29, 0x0a, 0x06, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x76,
	0x31, 0x2e, 0x4d, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x06, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x42,
	0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x6e,
	0x65, 0x78, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x2f, 0x6f, 0x6e, 0x65, 0x78, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x76, 0x31, 0x3b,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gateway_v1_miner_proto_rawDescOnce sync.Once
	file_gateway_v1_miner_proto_rawDescData = file_gateway_v1_miner_proto_rawDesc
)

func file_gateway_v1_miner_proto_rawDescGZIP() []byte {
	file_gateway_v1_miner_proto_rawDescOnce.Do(func() {
		file_gateway_v1_miner_proto_rawDescData = protoimpl.X.CompressGZIP(file_gateway_v1_miner_proto_rawDescData)
	})
	return file_gateway_v1_miner_proto_rawDescData
}

var file_gateway_v1_miner_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_gateway_v1_miner_proto_goTypes = []any{
	(*Miner)(nil),                 // 0: gateway.v1.Miner
	(*CreateMinerRequest)(nil),    // 1: gateway.v1.CreateMinerRequest
	(*UpdateMinerRequest)(nil),    // 2: gateway.v1.UpdateMinerRequest
	(*DeleteMinerRequest)(nil),    // 3: gateway.v1.DeleteMinerRequest
	(*DeleteMinerResponse)(nil),   // 4: gateway.v1.DeleteMinerResponse
	(*GetMinerRequest)(nil),       // 5: gateway.v1.GetMinerRequest
	(*GetMinerResponse)(nil),      // 6: gateway.v1.GetMinerResponse
	(*ListMinerRequest)(nil),      // 7: gateway.v1.ListMinerRequest
	(*ListMinerResponse)(nil),     // 8: gateway.v1.ListMinerResponse
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_gateway_v1_miner_proto_depIdxs = []int32{
	9, // 0: gateway.v1.Miner.createdAt:type_name -> google.protobuf.Timestamp
	9, // 1: gateway.v1.Miner.updatedAt:type_name -> google.protobuf.Timestamp
	0, // 2: gateway.v1.GetMinerResponse.miner:type_name -> gateway.v1.Miner
	0, // 3: gateway.v1.ListMinerResponse.miners:type_name -> gateway.v1.Miner
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_gateway_v1_miner_proto_init() }
func file_gateway_v1_miner_proto_init() {
	if File_gateway_v1_miner_proto != nil {
		return
	}
	file_gateway_v1_miner_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gateway_v1_miner_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_v1_miner_proto_goTypes,
		DependencyIndexes: file_gateway_v1_miner_proto_depIdxs,
		MessageInfos:      file_gateway_v1_miner_proto_msgTypes,
	}.Build()
	File_gateway_v1_miner_proto = out.File
	file_gateway_v1_miner_proto_rawDesc = nil
	file_gateway_v1_miner_proto_goTypes = nil
	file_gateway_v1_miner_proto_depIdxs = nil
}
