// Code generated by protoc-gen-deepcopy. DO NOT EDIT.

package v1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using Miner within kubernetes types, where deepcopy-gen is used.
func (in *Miner) DeepCopyInto(out *Miner) {
	p := proto.Clone(in).(*Miner)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Miner. Required by controller-gen.
func (in *Miner) DeepCopy() *Miner {
	if in == nil {
		return nil
	}
	out := new(Miner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Miner. Required by controller-gen.
func (in *Miner) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using CreateMinerRequest within kubernetes types, where deepcopy-gen is used.
func (in *CreateMinerRequest) DeepCopyInto(out *CreateMinerRequest) {
	p := proto.Clone(in).(*CreateMinerRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateMinerRequest. Required by controller-gen.
func (in *CreateMinerRequest) DeepCopy() *CreateMinerRequest {
	if in == nil {
		return nil
	}
	out := new(CreateMinerRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new CreateMinerRequest. Required by controller-gen.
func (in *CreateMinerRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateMinerRequest within kubernetes types, where deepcopy-gen is used.
func (in *UpdateMinerRequest) DeepCopyInto(out *UpdateMinerRequest) {
	p := proto.Clone(in).(*UpdateMinerRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateMinerRequest. Required by controller-gen.
func (in *UpdateMinerRequest) DeepCopy() *UpdateMinerRequest {
	if in == nil {
		return nil
	}
	out := new(UpdateMinerRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateMinerRequest. Required by controller-gen.
func (in *UpdateMinerRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DeleteMinerRequest within kubernetes types, where deepcopy-gen is used.
func (in *DeleteMinerRequest) DeepCopyInto(out *DeleteMinerRequest) {
	p := proto.Clone(in).(*DeleteMinerRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteMinerRequest. Required by controller-gen.
func (in *DeleteMinerRequest) DeepCopy() *DeleteMinerRequest {
	if in == nil {
		return nil
	}
	out := new(DeleteMinerRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DeleteMinerRequest. Required by controller-gen.
func (in *DeleteMinerRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DeleteMinerResponse within kubernetes types, where deepcopy-gen is used.
func (in *DeleteMinerResponse) DeepCopyInto(out *DeleteMinerResponse) {
	p := proto.Clone(in).(*DeleteMinerResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteMinerResponse. Required by controller-gen.
func (in *DeleteMinerResponse) DeepCopy() *DeleteMinerResponse {
	if in == nil {
		return nil
	}
	out := new(DeleteMinerResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DeleteMinerResponse. Required by controller-gen.
func (in *DeleteMinerResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetMinerRequest within kubernetes types, where deepcopy-gen is used.
func (in *GetMinerRequest) DeepCopyInto(out *GetMinerRequest) {
	p := proto.Clone(in).(*GetMinerRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetMinerRequest. Required by controller-gen.
func (in *GetMinerRequest) DeepCopy() *GetMinerRequest {
	if in == nil {
		return nil
	}
	out := new(GetMinerRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetMinerRequest. Required by controller-gen.
func (in *GetMinerRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetMinerResponse within kubernetes types, where deepcopy-gen is used.
func (in *GetMinerResponse) DeepCopyInto(out *GetMinerResponse) {
	p := proto.Clone(in).(*GetMinerResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetMinerResponse. Required by controller-gen.
func (in *GetMinerResponse) DeepCopy() *GetMinerResponse {
	if in == nil {
		return nil
	}
	out := new(GetMinerResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetMinerResponse. Required by controller-gen.
func (in *GetMinerResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ListMinerRequest within kubernetes types, where deepcopy-gen is used.
func (in *ListMinerRequest) DeepCopyInto(out *ListMinerRequest) {
	p := proto.Clone(in).(*ListMinerRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListMinerRequest. Required by controller-gen.
func (in *ListMinerRequest) DeepCopy() *ListMinerRequest {
	if in == nil {
		return nil
	}
	out := new(ListMinerRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ListMinerRequest. Required by controller-gen.
func (in *ListMinerRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ListMinerResponse within kubernetes types, where deepcopy-gen is used.
func (in *ListMinerResponse) DeepCopyInto(out *ListMinerResponse) {
	p := proto.Clone(in).(*ListMinerResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListMinerResponse. Required by controller-gen.
func (in *ListMinerResponse) DeepCopy() *ListMinerResponse {
	if in == nil {
		return nil
	}
	out := new(ListMinerResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ListMinerResponse. Required by controller-gen.
func (in *ListMinerResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
