// This file defines the Protobuf messages for managing Miners.
//

// Code generated by protoc-gen-defaults. DO NOT EDIT.

package v1

import (
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

var (
	_ *timestamppb.Timestamp
	_ *durationpb.Duration
	_ *wrapperspb.BoolValue
)

func (x *Miner) Default() {
}

func (x *CreateMinerRequest) Default() {
}

func (x *UpdateMinerRequest) Default() {
}

func (x *DeleteMinerRequest) Default() {
}

func (x *DeleteMinerResponse) Default() {
}

func (x *GetMinerRequest) Default() {
}

func (x *GetMinerResponse) Default() {
}

func (x *ListMinerRequest) Default() {
}

func (x *ListMinerResponse) Default() {
}
