// Code generated by protoc-gen-deepcopy. DO NOT EDIT.

package v1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using Order within kubernetes types, where deepcopy-gen is used.
func (in *Order) DeepCopyInto(out *Order) {
	p := proto.Clone(in).(*Order)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Order. Required by controller-gen.
func (in *Order) DeepCopy() *Order {
	if in == nil {
		return nil
	}
	out := new(Order)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Order. Required by controller-gen.
func (in *Order) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using CreateOrderRequest within kubernetes types, where deepcopy-gen is used.
func (in *CreateOrderRequest) DeepCopyInto(out *CreateOrderRequest) {
	p := proto.Clone(in).(*CreateOrderRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateOrderRequest. Required by controller-gen.
func (in *CreateOrderRequest) DeepCopy() *CreateOrderRequest {
	if in == nil {
		return nil
	}
	out := new(CreateOrderRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new CreateOrderRequest. Required by controller-gen.
func (in *CreateOrderRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using CreateOrderResponse within kubernetes types, where deepcopy-gen is used.
func (in *CreateOrderResponse) DeepCopyInto(out *CreateOrderResponse) {
	p := proto.Clone(in).(*CreateOrderResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateOrderResponse. Required by controller-gen.
func (in *CreateOrderResponse) DeepCopy() *CreateOrderResponse {
	if in == nil {
		return nil
	}
	out := new(CreateOrderResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new CreateOrderResponse. Required by controller-gen.
func (in *CreateOrderResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateOrderRequest within kubernetes types, where deepcopy-gen is used.
func (in *UpdateOrderRequest) DeepCopyInto(out *UpdateOrderRequest) {
	p := proto.Clone(in).(*UpdateOrderRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateOrderRequest. Required by controller-gen.
func (in *UpdateOrderRequest) DeepCopy() *UpdateOrderRequest {
	if in == nil {
		return nil
	}
	out := new(UpdateOrderRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateOrderRequest. Required by controller-gen.
func (in *UpdateOrderRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateOrderResponse within kubernetes types, where deepcopy-gen is used.
func (in *UpdateOrderResponse) DeepCopyInto(out *UpdateOrderResponse) {
	p := proto.Clone(in).(*UpdateOrderResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateOrderResponse. Required by controller-gen.
func (in *UpdateOrderResponse) DeepCopy() *UpdateOrderResponse {
	if in == nil {
		return nil
	}
	out := new(UpdateOrderResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateOrderResponse. Required by controller-gen.
func (in *UpdateOrderResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DeleteOrderRequest within kubernetes types, where deepcopy-gen is used.
func (in *DeleteOrderRequest) DeepCopyInto(out *DeleteOrderRequest) {
	p := proto.Clone(in).(*DeleteOrderRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteOrderRequest. Required by controller-gen.
func (in *DeleteOrderRequest) DeepCopy() *DeleteOrderRequest {
	if in == nil {
		return nil
	}
	out := new(DeleteOrderRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DeleteOrderRequest. Required by controller-gen.
func (in *DeleteOrderRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DeleteOrderResponse within kubernetes types, where deepcopy-gen is used.
func (in *DeleteOrderResponse) DeepCopyInto(out *DeleteOrderResponse) {
	p := proto.Clone(in).(*DeleteOrderResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteOrderResponse. Required by controller-gen.
func (in *DeleteOrderResponse) DeepCopy() *DeleteOrderResponse {
	if in == nil {
		return nil
	}
	out := new(DeleteOrderResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DeleteOrderResponse. Required by controller-gen.
func (in *DeleteOrderResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetOrderRequest within kubernetes types, where deepcopy-gen is used.
func (in *GetOrderRequest) DeepCopyInto(out *GetOrderRequest) {
	p := proto.Clone(in).(*GetOrderRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetOrderRequest. Required by controller-gen.
func (in *GetOrderRequest) DeepCopy() *GetOrderRequest {
	if in == nil {
		return nil
	}
	out := new(GetOrderRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetOrderRequest. Required by controller-gen.
func (in *GetOrderRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetOrderResponse within kubernetes types, where deepcopy-gen is used.
func (in *GetOrderResponse) DeepCopyInto(out *GetOrderResponse) {
	p := proto.Clone(in).(*GetOrderResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetOrderResponse. Required by controller-gen.
func (in *GetOrderResponse) DeepCopy() *GetOrderResponse {
	if in == nil {
		return nil
	}
	out := new(GetOrderResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetOrderResponse. Required by controller-gen.
func (in *GetOrderResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ListOrderRequest within kubernetes types, where deepcopy-gen is used.
func (in *ListOrderRequest) DeepCopyInto(out *ListOrderRequest) {
	p := proto.Clone(in).(*ListOrderRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListOrderRequest. Required by controller-gen.
func (in *ListOrderRequest) DeepCopy() *ListOrderRequest {
	if in == nil {
		return nil
	}
	out := new(ListOrderRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ListOrderRequest. Required by controller-gen.
func (in *ListOrderRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ListOrderResponse within kubernetes types, where deepcopy-gen is used.
func (in *ListOrderResponse) DeepCopyInto(out *ListOrderResponse) {
	p := proto.Clone(in).(*ListOrderResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListOrderResponse. Required by controller-gen.
func (in *ListOrderResponse) DeepCopy() *ListOrderResponse {
	if in == nil {
		return nil
	}
	out := new(ListOrderResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ListOrderResponse. Required by controller-gen.
func (in *ListOrderResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
