// Code generated by protoc-gen-deepcopy. DO NOT EDIT.

package v1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using SetRequest within kubernetes types, where deepcopy-gen is used.
func (in *SetRequest) DeepCopyInto(out *SetRequest) {
	p := proto.Clone(in).(*SetRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SetRequest. Required by controller-gen.
func (in *SetRequest) DeepCopy() *SetRequest {
	if in == nil {
		return nil
	}
	out := new(SetRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new SetRequest. Required by controller-gen.
func (in *SetRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DelRequest within kubernetes types, where deepcopy-gen is used.
func (in *DelRequest) DeepCopyInto(out *DelRequest) {
	p := proto.Clone(in).(*DelRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DelRequest. Required by controller-gen.
func (in *DelRequest) DeepCopy() *DelRequest {
	if in == nil {
		return nil
	}
	out := new(DelRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DelRequest. Required by controller-gen.
func (in *DelRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetRequest within kubernetes types, where deepcopy-gen is used.
func (in *GetRequest) DeepCopyInto(out *GetRequest) {
	p := proto.Clone(in).(*GetRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetRequest. Required by controller-gen.
func (in *GetRequest) DeepCopy() *GetRequest {
	if in == nil {
		return nil
	}
	out := new(GetRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetRequest. Required by controller-gen.
func (in *GetRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetResponse within kubernetes types, where deepcopy-gen is used.
func (in *GetResponse) DeepCopyInto(out *GetResponse) {
	p := proto.Clone(in).(*GetResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetResponse. Required by controller-gen.
func (in *GetResponse) DeepCopy() *GetResponse {
	if in == nil {
		return nil
	}
	out := new(GetResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetResponse. Required by controller-gen.
func (in *GetResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
