// Code generated by protoc-gen-deepcopy. DO NOT EDIT.

package v1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using CreateBlockRequest within kubernetes types, where deepcopy-gen is used.
func (in *CreateBlockRequest) DeepCopyInto(out *CreateBlockRequest) {
	p := proto.Clone(in).(*CreateBlockRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateBlockRequest. Required by controller-gen.
func (in *CreateBlockRequest) DeepCopy() *CreateBlockRequest {
	if in == nil {
		return nil
	}
	out := new(CreateBlockRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new CreateBlockRequest. Required by controller-gen.
func (in *CreateBlockRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using CreatePeerRequest within kubernetes types, where deepcopy-gen is used.
func (in *CreatePeerRequest) DeepCopyInto(out *CreatePeerRequest) {
	p := proto.Clone(in).(*CreatePeerRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreatePeerRequest. Required by controller-gen.
func (in *CreatePeerRequest) DeepCopy() *CreatePeerRequest {
	if in == nil {
		return nil
	}
	out := new(CreatePeerRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new CreatePeerRequest. Required by controller-gen.
func (in *CreatePeerRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
