// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMinerSetM = "gateway_minerset"

// MinerSetM mapped from table <gateway_minerset>
type MinerSetM struct {
	ID                   int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键 ID" json:"id"`                     // 主键 ID
	Namespace            string    `gorm:"column:namespace;not null;comment:命名空间" json:"namespace"`                             // 命名空间
	Name                 string    `gorm:"column:name;not null;comment:矿机池名" json:"name"`                                       // 矿机池名
	Replicas             int32     `gorm:"column:replicas;not null;comment:矿机副本数" json:"replicas"`                              // 矿机副本数
	DisplayName          string    `gorm:"column:displayName;not null;comment:矿机池展示名" json:"displayName"`                       // 矿机池展示名
	DeletePolicy         string    `gorm:"column:deletePolicy;not null;comment:矿机池缩容策略" json:"deletePolicy"`                    // 矿机池缩容策略
	MinReadySeconds      int32     `gorm:"column:minReadySeconds;not null;comment:矿机 Ready 最小等待时间" json:"minReadySeconds"`      // 矿机 Ready 最小等待时间
	FullyLabeledReplicas int32     `gorm:"column:fullyLabeledReplicas;not null;comment:所有标签匹配的副本数" json:"fullyLabeledReplicas"` // 所有标签匹配的副本数
	ReadyReplicas        int32     `gorm:"column:readyReplicas;not null;comment:Ready 副本数" json:"readyReplicas"`                // Ready 副本数
	AvailableReplicas    int32     `gorm:"column:availableReplicas;not null;comment:可用副本数" json:"availableReplicas"`            // 可用副本数
	FailureReason        *string   `gorm:"column:failureReason;comment:失败原因" json:"failureReason"`                              // 失败原因
	FailureMessage       *string   `gorm:"column:failureMessage;comment:失败信息" json:"failureMessage"`                            // 失败信息
	Conditions           *string   `gorm:"column:conditions;comment:矿机池状态" json:"conditions"`                                   // 矿机池状态
	CreatedAt            time.Time `gorm:"column:createdAt;not null;default:current_timestamp;comment:创建时间" json:"createdAt"`   // 创建时间
	UpdatedAt            time.Time `gorm:"column:updatedAt;not null;default:current_timestamp;comment:最后修改时间" json:"updatedAt"` // 最后修改时间
}

// TableName MinerSetM's table name
func (*MinerSetM) TableName() string {
	return TableNameMinerSetM
}
