// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/onexstack/onex/internal/gateway/store"
	"github.com/onexstack/onexstack/pkg/db"
)

// Injectors from wire.go:

func wireStoreClient(mySQLOptions *db.MySQLOptions) (store.IStore, error) {
	gormDB, err := db.NewMySQL(mySQLOptions)
	if err != nil {
		return nil, err
	}
	datastore := store.NewStore(gormDB)
	return datastore, nil
}
