// Code generated by protoc-gen-deepcopy. DO NOT EDIT.

package v1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using Secret within kubernetes types, where deepcopy-gen is used.
func (in *Secret) DeepCopyInto(out *Secret) {
	p := proto.Clone(in).(*Secret)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Secret. Required by controller-gen.
func (in *Secret) DeepCopy() *Secret {
	if in == nil {
		return nil
	}
	out := new(Secret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Secret. Required by controller-gen.
func (in *Secret) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using CreateSecretRequest within kubernetes types, where deepcopy-gen is used.
func (in *CreateSecretRequest) DeepCopyInto(out *CreateSecretRequest) {
	p := proto.Clone(in).(*CreateSecretRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateSecretRequest. Required by controller-gen.
func (in *CreateSecretRequest) DeepCopy() *CreateSecretRequest {
	if in == nil {
		return nil
	}
	out := new(CreateSecretRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new CreateSecretRequest. Required by controller-gen.
func (in *CreateSecretRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using CreateSecretResponse within kubernetes types, where deepcopy-gen is used.
func (in *CreateSecretResponse) DeepCopyInto(out *CreateSecretResponse) {
	p := proto.Clone(in).(*CreateSecretResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateSecretResponse. Required by controller-gen.
func (in *CreateSecretResponse) DeepCopy() *CreateSecretResponse {
	if in == nil {
		return nil
	}
	out := new(CreateSecretResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new CreateSecretResponse. Required by controller-gen.
func (in *CreateSecretResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateSecretRequest within kubernetes types, where deepcopy-gen is used.
func (in *UpdateSecretRequest) DeepCopyInto(out *UpdateSecretRequest) {
	p := proto.Clone(in).(*UpdateSecretRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateSecretRequest. Required by controller-gen.
func (in *UpdateSecretRequest) DeepCopy() *UpdateSecretRequest {
	if in == nil {
		return nil
	}
	out := new(UpdateSecretRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateSecretRequest. Required by controller-gen.
func (in *UpdateSecretRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateSecretResponse within kubernetes types, where deepcopy-gen is used.
func (in *UpdateSecretResponse) DeepCopyInto(out *UpdateSecretResponse) {
	p := proto.Clone(in).(*UpdateSecretResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateSecretResponse. Required by controller-gen.
func (in *UpdateSecretResponse) DeepCopy() *UpdateSecretResponse {
	if in == nil {
		return nil
	}
	out := new(UpdateSecretResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateSecretResponse. Required by controller-gen.
func (in *UpdateSecretResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DeleteSecretRequest within kubernetes types, where deepcopy-gen is used.
func (in *DeleteSecretRequest) DeepCopyInto(out *DeleteSecretRequest) {
	p := proto.Clone(in).(*DeleteSecretRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteSecretRequest. Required by controller-gen.
func (in *DeleteSecretRequest) DeepCopy() *DeleteSecretRequest {
	if in == nil {
		return nil
	}
	out := new(DeleteSecretRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DeleteSecretRequest. Required by controller-gen.
func (in *DeleteSecretRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DeleteSecretResponse within kubernetes types, where deepcopy-gen is used.
func (in *DeleteSecretResponse) DeepCopyInto(out *DeleteSecretResponse) {
	p := proto.Clone(in).(*DeleteSecretResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteSecretResponse. Required by controller-gen.
func (in *DeleteSecretResponse) DeepCopy() *DeleteSecretResponse {
	if in == nil {
		return nil
	}
	out := new(DeleteSecretResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DeleteSecretResponse. Required by controller-gen.
func (in *DeleteSecretResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetSecretRequest within kubernetes types, where deepcopy-gen is used.
func (in *GetSecretRequest) DeepCopyInto(out *GetSecretRequest) {
	p := proto.Clone(in).(*GetSecretRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetSecretRequest. Required by controller-gen.
func (in *GetSecretRequest) DeepCopy() *GetSecretRequest {
	if in == nil {
		return nil
	}
	out := new(GetSecretRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetSecretRequest. Required by controller-gen.
func (in *GetSecretRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetSecretResponse within kubernetes types, where deepcopy-gen is used.
func (in *GetSecretResponse) DeepCopyInto(out *GetSecretResponse) {
	p := proto.Clone(in).(*GetSecretResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetSecretResponse. Required by controller-gen.
func (in *GetSecretResponse) DeepCopy() *GetSecretResponse {
	if in == nil {
		return nil
	}
	out := new(GetSecretResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetSecretResponse. Required by controller-gen.
func (in *GetSecretResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ListSecretRequest within kubernetes types, where deepcopy-gen is used.
func (in *ListSecretRequest) DeepCopyInto(out *ListSecretRequest) {
	p := proto.Clone(in).(*ListSecretRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListSecretRequest. Required by controller-gen.
func (in *ListSecretRequest) DeepCopy() *ListSecretRequest {
	if in == nil {
		return nil
	}
	out := new(ListSecretRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ListSecretRequest. Required by controller-gen.
func (in *ListSecretRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ListSecretResponse within kubernetes types, where deepcopy-gen is used.
func (in *ListSecretResponse) DeepCopyInto(out *ListSecretResponse) {
	p := proto.Clone(in).(*ListSecretResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListSecretResponse. Required by controller-gen.
func (in *ListSecretResponse) DeepCopy() *ListSecretResponse {
	if in == nil {
		return nil
	}
	out := new(ListSecretResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ListSecretResponse. Required by controller-gen.
func (in *ListSecretResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
