// This file defines the Protobuf messages for managing Secrets.
//

// Code generated by protoc-gen-defaults. DO NOT EDIT.

package v1

import (
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

var (
	_ *timestamppb.Timestamp
	_ *durationpb.Duration
	_ *wrapperspb.BoolValue
)

func (x *Secret) Default() {
}

func (x *CreateSecretRequest) Default() {
}

func (x *CreateSecretResponse) Default() {
}

func (x *UpdateSecretRequest) Default() {
}

func (x *UpdateSecretResponse) Default() {
}

func (x *DeleteSecretRequest) Default() {
}

func (x *DeleteSecretResponse) Default() {
}

func (x *GetSecretRequest) Default() {
}

func (x *GetSecretResponse) Default() {
}

func (x *ListSecretRequest) Default() {
}

func (x *ListSecretResponse) Default() {
}
