# Copyright 2022 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file. The original repo for
# this file is https://github.com/onexstack/onex.
#


apiVersion: blockchaincontroller.config.onex.io/v1beta1
kind: BlockchainControllerConfiguration
generic:
  metricsBindAddress: 0.0.0.0:${ONEX_BLOCKCHAIN_CONTROLLER_METRICS_PORT}
  healthzBindAddress: 0.0.0.0:${ONEX_BLOCKCHAIN_CONTROLLER_HEALTHZ_PORT}
  parallelism: 32
  leaderElection: 
    leaderElect: false
dryRun: true
providerKubeconfig: /opt/onex/etc/config.kind
redis:
  addr: ${ONEX_REDIS_ADDR}
  database: ${ONEX_BLOCKCHAIN_CONTROLLER_REDIS_DATABASE}
  password: ${ONEX_REDIS_PASSWORD}
mysql: 
  host: ${ONEX_MYSQL_ADDR}
  database: ${ONEX_MYSQL_DATABASE}
  username: ${ONEX_MYSQL_USERNAME}
  password: ${ONEX_MYSQL_PASSWORD}
types:
  S1.SMALL1: 
    # CPU, in cores. (500m = .5 cores)
    cpu: 50m
    # Memory, in bytes. (500Gi = 500GiB = 500 * 1024 * 1024 * 1024)
    memory: 1024Mi
    miningDifficulty: 1
  S1.SMALL2: 
    cpu: 100m
    memory: 1024Mi
    miningDifficulty: 1
  M1.MEDIUM1: 
    cpu: 150m
    memory: 1024Mi
    miningDifficulty: 1
  M1.MEDIUM2: 
    cpu: 200m
    memory: 2048Mi
    miningDifficulty: 1
