// Code generated by protoc-gen-deepcopy. DO NOT EDIT.

package v1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using CronJob within kubernetes types, where deepcopy-gen is used.
func (in *CronJob) DeepCopyInto(out *CronJob) {
	p := proto.Clone(in).(*CronJob)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronJob. Required by controller-gen.
func (in *CronJob) DeepCopy() *CronJob {
	if in == nil {
		return nil
	}
	out := new(CronJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new CronJob. Required by controller-gen.
func (in *CronJob) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using CronJobStatus within kubernetes types, where deepcopy-gen is used.
func (in *CronJobStatus) DeepCopyInto(out *CronJobStatus) {
	p := proto.Clone(in).(*CronJobStatus)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronJobStatus. Required by controller-gen.
func (in *CronJobStatus) DeepCopy() *CronJobStatus {
	if in == nil {
		return nil
	}
	out := new(CronJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new CronJobStatus. Required by controller-gen.
func (in *CronJobStatus) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using CreateCronJobRequest within kubernetes types, where deepcopy-gen is used.
func (in *CreateCronJobRequest) DeepCopyInto(out *CreateCronJobRequest) {
	p := proto.Clone(in).(*CreateCronJobRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateCronJobRequest. Required by controller-gen.
func (in *CreateCronJobRequest) DeepCopy() *CreateCronJobRequest {
	if in == nil {
		return nil
	}
	out := new(CreateCronJobRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new CreateCronJobRequest. Required by controller-gen.
func (in *CreateCronJobRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using CreateCronJobResponse within kubernetes types, where deepcopy-gen is used.
func (in *CreateCronJobResponse) DeepCopyInto(out *CreateCronJobResponse) {
	p := proto.Clone(in).(*CreateCronJobResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateCronJobResponse. Required by controller-gen.
func (in *CreateCronJobResponse) DeepCopy() *CreateCronJobResponse {
	if in == nil {
		return nil
	}
	out := new(CreateCronJobResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new CreateCronJobResponse. Required by controller-gen.
func (in *CreateCronJobResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateCronJobRequest within kubernetes types, where deepcopy-gen is used.
func (in *UpdateCronJobRequest) DeepCopyInto(out *UpdateCronJobRequest) {
	p := proto.Clone(in).(*UpdateCronJobRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateCronJobRequest. Required by controller-gen.
func (in *UpdateCronJobRequest) DeepCopy() *UpdateCronJobRequest {
	if in == nil {
		return nil
	}
	out := new(UpdateCronJobRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateCronJobRequest. Required by controller-gen.
func (in *UpdateCronJobRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateCronJobResponse within kubernetes types, where deepcopy-gen is used.
func (in *UpdateCronJobResponse) DeepCopyInto(out *UpdateCronJobResponse) {
	p := proto.Clone(in).(*UpdateCronJobResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateCronJobResponse. Required by controller-gen.
func (in *UpdateCronJobResponse) DeepCopy() *UpdateCronJobResponse {
	if in == nil {
		return nil
	}
	out := new(UpdateCronJobResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateCronJobResponse. Required by controller-gen.
func (in *UpdateCronJobResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DeleteCronJobRequest within kubernetes types, where deepcopy-gen is used.
func (in *DeleteCronJobRequest) DeepCopyInto(out *DeleteCronJobRequest) {
	p := proto.Clone(in).(*DeleteCronJobRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteCronJobRequest. Required by controller-gen.
func (in *DeleteCronJobRequest) DeepCopy() *DeleteCronJobRequest {
	if in == nil {
		return nil
	}
	out := new(DeleteCronJobRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DeleteCronJobRequest. Required by controller-gen.
func (in *DeleteCronJobRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DeleteCronJobResponse within kubernetes types, where deepcopy-gen is used.
func (in *DeleteCronJobResponse) DeepCopyInto(out *DeleteCronJobResponse) {
	p := proto.Clone(in).(*DeleteCronJobResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteCronJobResponse. Required by controller-gen.
func (in *DeleteCronJobResponse) DeepCopy() *DeleteCronJobResponse {
	if in == nil {
		return nil
	}
	out := new(DeleteCronJobResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DeleteCronJobResponse. Required by controller-gen.
func (in *DeleteCronJobResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetCronJobRequest within kubernetes types, where deepcopy-gen is used.
func (in *GetCronJobRequest) DeepCopyInto(out *GetCronJobRequest) {
	p := proto.Clone(in).(*GetCronJobRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetCronJobRequest. Required by controller-gen.
func (in *GetCronJobRequest) DeepCopy() *GetCronJobRequest {
	if in == nil {
		return nil
	}
	out := new(GetCronJobRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetCronJobRequest. Required by controller-gen.
func (in *GetCronJobRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetCronJobResponse within kubernetes types, where deepcopy-gen is used.
func (in *GetCronJobResponse) DeepCopyInto(out *GetCronJobResponse) {
	p := proto.Clone(in).(*GetCronJobResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetCronJobResponse. Required by controller-gen.
func (in *GetCronJobResponse) DeepCopy() *GetCronJobResponse {
	if in == nil {
		return nil
	}
	out := new(GetCronJobResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetCronJobResponse. Required by controller-gen.
func (in *GetCronJobResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ListCronJobRequest within kubernetes types, where deepcopy-gen is used.
func (in *ListCronJobRequest) DeepCopyInto(out *ListCronJobRequest) {
	p := proto.Clone(in).(*ListCronJobRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListCronJobRequest. Required by controller-gen.
func (in *ListCronJobRequest) DeepCopy() *ListCronJobRequest {
	if in == nil {
		return nil
	}
	out := new(ListCronJobRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ListCronJobRequest. Required by controller-gen.
func (in *ListCronJobRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ListCronJobResponse within kubernetes types, where deepcopy-gen is used.
func (in *ListCronJobResponse) DeepCopyInto(out *ListCronJobResponse) {
	p := proto.Clone(in).(*ListCronJobResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListCronJobResponse. Required by controller-gen.
func (in *ListCronJobResponse) DeepCopy() *ListCronJobResponse {
	if in == nil {
		return nil
	}
	out := new(ListCronJobResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ListCronJobResponse. Required by controller-gen.
func (in *ListCronJobResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
