// Code generated by protoc-gen-defaults. DO NOT EDIT.

package v1

import (
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

var (
	_ *timestamppb.Timestamp
	_ *durationpb.Duration
	_ *wrapperspb.BoolValue
)

func (x *Job) Default() {
}

func (x *JobParams) Default() {
}

func (x *TrainParams) Default() {
}

func (x *JobResults) Default() {
}

func (x *TrainResults) Default() {
}

func (x *JobCondition) Default() {
}

func (x *CreateJobRequest) Default() {
}

func (x *CreateJobResponse) Default() {
}

func (x *UpdateJobRequest) Default() {
}

func (x *UpdateJobResponse) Default() {
}

func (x *DeleteJobRequest) Default() {
}

func (x *DeleteJobResponse) Default() {
}

func (x *GetJobRequest) Default() {
}

func (x *GetJobResponse) Default() {
}

func (x *ListJobRequest) Default() {
}

func (x *ListJobResponse) Default() {
}
